name: CreateInstaller
on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output version
        id: version
        run: |
          VER=$(awk 'BEGIN{ORS=""}/version/{print $NF}' version.ini)
          echo "version=$VER" >> $GITHUB_OUTPUT
      - name: Create setup32.exe and output FN
        id: filename
        run: |
          7z a sat.7z * -x@3rdparty/excludefiles.txt
          FN32="sat-v${{ steps.version.outputs.version }}-setup32.exe"
          cat 3rdparty/7zSDx86.sfx 3rdparty/config.txt sat.7z > $FN32
          echo "filename=$FN32" >> $GITHUB_OUTPUT
      - name: Release new
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          files: ${{ steps.filename.outputs.filename }}
          body: ${{ github.event.head_commit.message }}
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: eMail Test
        uses: dawidd6/action-send-mail@v3
        with:
          # smtp://user:password@server:port
          connection_url: ${{ secrets.MAIL_CONNECTION_SMTP }}
          subject: GdvE-Audiomanager (v${{ steps.version.outputs.version }}) wurde released
          to: Simon Brenner <herrpi@gmail.com>
          from: Github GAM Pipeline <mailservice@gdve-kl.de>
          # Optional plain body:
          body: |
            ${{ github.repository }} » ${{ github.ref_name }} - [Build # ${{ github.run_number }}][1] - ${{ job.status }}

            Commit: ${{ github.sha }}

            [1]: ${{ github.event.head_commit.url }}
          html_body: |
            ${{ github.repository }} » ${{ github.ref_name }} - [Build # ${{ github.run_number }}](${{ github.event.head_commit.url }}) - ${{ job.status }}

            Commit: **${{ github.sha }}**

            Dies ist der plain body für v${{ steps.version.outputs.version }}

            Letzter Commit: ${{ github.event.head_commit.message }}

            Author: ${{ github.event.head_commit.author.name }}

            Added: ${{ github.event.head_commit.added }}

            Mod: ${{ github.event.head_commit.modified }}

            URL: ${{ github.event.head_commit.url }}
          convert_markdown: true
          #            Dies ist der plain body für v${{ steps.version.outputs.version }}
          #            Letzter Commit: ${{ github.event.head_commit.message }}
          #            Author: ${{ github.event.head_commit.author.name }}
          #            Added: ${{ github.event.head_commit.added }}
          #            Mod: ${{ github.event.head_commit.modified }}
          #            URL: ${{ github.event.head_commit.url }}
          # Optional HTML body read from file:
          #html_body: file://email.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
