name: CreateInstaller
on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Output version
        id: version
        run: |
          VER=$(awk 'BEGIN{ORS=""}/version/{print $NF}' version.ini)
          echo "version=$VER" >> $GITHUB_OUTPUT
      - name: Create setup32.exe and output FN
        id: filename
        run: |
          7z a sat.7z * -x@3rdparty/excludefiles.txt
          FN32="sat-v${{ steps.version.outputs.version }}-setup32.exe"
          cat 3rdparty/7zSDx86.sfx 3rdparty/config.txt sat.7z > $FN32
          echo "filename=$FN32" >> $GITHUB_OUTPUT
      - name: Release new
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          files: ${{ steps.filename.outputs.filename }}
          body: ${{ github.event.head_commit.message }}
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: eMail Test
        uses: dawidd6/action-send-mail@v3
        with:
          # smtp://user:password@server:port
          connection_url: ${{ secrets.MAIL_CONNECTION_SMTP }}
          subject: GdvE-Audiomanager (v${{ steps.version.outputs.version }}) wurde released
          to: Simon Brenner <herrpi@gmail.com>
          from: Github GAM Pipeline <mailservice@gdve-kl.de>
          # Optional plain body:
          #body: |
          html_body: |
            Hallo Freunde,

            ein neuer <b>GdvE-Audiomanager</b> (v${{ steps.version.outputs.version }}) steht zum Download bereit:<br />
            https://github.com/HerrPi/actiontest/releases/download/v${{ steps.version.outputs.version }}/${{ steps.filename.outputs.filename }}

            Die letzte Commit Message lautet:<br />
            <i>"${{ github.event.head_commit.message }}"</i>

            Falls euch die Änderungsdetails interessieren, hier der Link zum Commit von ${{ github.event.head_commit.author.name }}:<br />
            ${{ github.event.head_commit.url }}

            Viele Grüße aus der Github Action.
          convert_markdown: true
          # Optional HTML body read from file:
          #html_body: file://email.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          #bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
